export const GET_CARDS = "GET_CARDS";
export const UPLOAD_CARDS = "UPLOAD_CARDS";
export const REMOVE_CARDS = "REMOVE_CARDS";

export const GET_LIKES = "GET_LIKES";
export const REMOVE_LIKES = "REMOVE_LIKES";

export const GET_USER = "GET_USER";
export const SET_USER = "SET_USER";

export const GET_AVATAR = "GET_AVATAR";
export const SET_AVATAR = "SET_AVATAR";

export const REQUEST = "_REQUEST";
export const SUCCESS = "_SUCCESS";
export const FAILURE = "_FAILURE";

export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";

export const GET_CARDS_REQUEST = "GET_CARDS_REQUEST";
export const GET_CARDS_SUCCESS = "GET_CARDS_SUCCESS";
export const GET_CARDS_FAILURE = "GET_CARDS_FAILURE";

export const PUT_LIKES_REQUEST = "PUT_LIKES_REQUEST";
export const PUT_LIKES_SUCCESS = "PUT_LIKES_SUCCESS";
export const PUT_LIKES_FAILURE = "PUT_LIKES_FAILURE";

export const REMOVE_LIKES_REQUEST = "REMOVE_LIKES_REQUEST";
export const REMOVE_LIKES_SUCCESS = "REMOVE_LIKES_SUCCESS";
export const REMOVE_LIKES_FAILURE = "REMOVE_LIKES_FAILURE";

export const DELETE_CARD_REQUEST = "DELETE_CARD_REQUEST";
export const DELETE_CARD_SUCCESS = "DELETE_CARD_SUCCESS";
export const DELETE_CARD_FAILURE = "DELETE_CARD_FAILURE";
